=== rmtuckerphx/badgerific/test/schemas/badgeDataSchema.json
{
    "$id": "BadgeDataSchema",
    "description": "Schema for BadgeData",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "props": {
            "$ref": "#/definitions/Props"
        },
        "systemProps": {
            "$ref": "#/definitions/Props"
        },
        "periods": {
            "type": "object"
        },
        "bookmarks": {
            "$ref": "#/definitions/Bookmarks"
        },
        "earned": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "lastEarned": {
                            "type": "string",
                            "pattern": "^([0-9]{4})-([0-9]{2})-([0-9]{2})T([0-9]{2}):([0-9]{2}):([0-9]{2}(?:\\.[0-9]*)?)((-([0-9]{2}):([0-9]{2})|Z)?)$"
                        },
                        "count": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "id",
                        "lastEarned",
                        "count"
                    ]
                }
            ]
        }
    },
    "required": [
        "systemProps",
        "props",
        "earned",
        "periods",
        "bookmarks"
    ],
    "definitions": {
        "Props": {
            "patternProperties": {
                "^.*$": {
                    "anyOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        },
                        {
                            "type": "boolean"
                        }
                    ]
                }
            },
            "additionalProperties": false
        },
        "Bookmarks": {
            "patternProperties": {
                "^.*$": {
                    "type": "string",
                    "pattern": "^([0-9]{4})-([0-9]{2})-([0-9]{2})T([0-9]{2}):([0-9]{2}):([0-9]{2}(?:\\.[0-9]*)?)((-([0-9]{2}):([0-9]{2})|Z)?)$"
                }
            },
            "additionalProperties": false
        }
    }
}

=== rmtuckerphx/badgerific/test/data/badgeData.json
{
    "systemProps": {
        "isNewYear": false,
        "isNewMonth": false,
        "isNewDay": false,
        "isNewHour": true,
        "isNewWeek": false,
        "isNewSession": false,
        "isSessionEnded": false,
        "sessionStatus": "IN_PROGRESS",
        "isNewGame": false,
        "isGameEnded": false,
        "gameStatus": "NONE",
        "date": "2022-07-10",
        "time": "20:30",
        "dayOfWeek": 7,
        "isWeekDay": false,
        "isWeekEnd": true,
        "lifetimeSessions": 1,
        "lifetimeGames": 8,
        "lifetimeGamesEnded": 0,
        "lifetimeGamesCanceled": 0,
        "lifetimeGameWins": 0,
        "lifetimeGameLoses": 0
    },
    "props": {},
    "periods": {
        "GLOBAL": {
            "key": "GLOBAL",
            "lastTimestamp": "1970-01-01T00:00:00.000Z"
        },
        "YEAR": {
            "key": "2022",
            "lastTimestamp": "2022-07-10T19:43:09.846Z"
        },
        "MONTH": {
            "key": "2022-07",
            "lastTimestamp": "2022-07-10T19:43:09.846Z"
        },
        "DAY": {
            "key": "2022-07-10",
            "lastTimestamp": "2022-07-10T19:43:09.846Z"
        },
        "HOUR": {
            "key": "2022-07-10-H20",
            "lastTimestamp": "2022-07-11T03:30:49.565Z"
        },
        "WEEK": {
            "key": "2022-W27",
            "lastTimestamp": "2022-07-10T19:43:09.846Z"
        },
        "SESSION": {
            "key": "0000000000000001",
            "lastTimestamp": "2022-07-11T03:30:49.566Z"
        },
        "GAME": {
            "key": "0000000000000008",
            "lastTimestamp": "2022-07-10T20:04:29.129Z"
        }
    },
    "earned": [
        {
            "id": "b01",
            "lastEarned": "2022-07-10T19:54:38.430Z",
            "count": 1
        }
    ],
    "bookmarks": {}
}
